apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
      run: kibana
  replicas: 1
  template:
    metadata:
      labels:
        run: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:6.2.1
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        - name: GET_HOSTS_FROM
          value: dns        
        - name: XPACK_SECURITY_ENABLED
          value: "false"
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
