apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    run: elasticsearch
spec:
  type: LoadBalancer
  selector:
    run: elasticsearch
  ports:
  - name: http-elastic
    port: 9200
    protocol: TCP
