apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
      tier: monitoring
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
        tier: monitoring
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
        imagePullPolicy: IfNotPresent
        env:
        - name: discovery.type
          value: single-node
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 9200
